<?php   $enable=$this->getStorelocatorEnabled();   ?>
<?php   $name=$this->getStorelocatorName();   ?>
<?php   $address=$this->getStorelocatorAddress();   ?>
<?php   $zipcode=$this->getStorelocatorZipcode();   ?>
<?php   $city=$this->getStorelocatorCity();   ?>
<?php   $country=$this->getStorelocatorCountry();   ?>
<?php   $phone=$this->getStorelocatorPhone();   ?>
<?php   $fax=$this->getStorelocatorFax();   ?>
<?php   $description=$this->getStorelocatorDescription();   ?>
<?php   $email=$this->getStorelocatorEmail();   ?>
<?php   $tradinghours=$this->getStorelocatorTradinghours();   ?>
<?php   $image=$this->getStorelocatorImage();   ?>
<?php   $stireurl=$this->getStorelocatorStoreurl();   ?>


<?php
$prefix = Mage::getConfig()->getTablePrefix();
$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
$prefix = Mage::getConfig()->getTablePrefix();
$tblname=$prefix.'manvstorelocator'; 
$sql1 = $connection->query("select * from $tblname order by id limit 1" ); 
$row1 = $sql1->fetch();
$latitudex = $row1['lat'];
$longitudex = $row1['longt'];
$addressx = $row1['address'];

if($row1['radius']=='')
{
$radius = 250;
}
else { 
$radius = $row1['radius'];
}
?>

<!--script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script--> 
<!--script src="https://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script-->
<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4nrGhAeKp3gSyVCnX25AqT7rYSaLKQpQ">
    </script>
<script type="text/javascript">
var markers = [];
var map;
function loadMap(x,y,a){

var miles = 3;
var latitude = x; // parseFloat("26.850883100000000000");
var longitude  = y; // parseFloat("75.824783600000040000");
var radius  = a; // "Rohini, New Delhi, Delhi, India";
var latlngPos = new google.maps.LatLng(latitude,longitude);
	
	map = new google.maps.Map(document.getElementById("map"), {
            zoom: 15,
            center: latlngPos,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }); 
	/*
	var circle = new google.maps.Circle({
            center: latlngPos,
            radius: miles *radius,
            fillColor: "#ff69b4",
            fillOpacity: 0.2,
            strokeOpacity: 0.0,
            strokeWeight: 0,
            map: map
        });*/
}
	
	
function map_xxx(x,y,a,index){

var miles = 3;
	var latitude = x; // parseFloat("26.850883100000000000");
	var longitude  = y; // parseFloat("75.824783600000040000");
  var radius  = a; // "Rohini, New Delhi, Delhi, India";
   
	var latlngPos = new google.maps.LatLng(latitude,longitude);
        
        // Set up options for the Google map
	/*
        var map = new google.maps.Map(document.getElementById("map"), {
            zoom: 14,

            center: latlngPos,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });    */
        // draw circle
/*
         var circle = new google.maps.Circle({
            center: latlngPos,
            radius: miles *radius,
            fillColor: "#ff69b4",
            fillOpacity: 0.2,
            strokeOpacity: 0.0,
            strokeWeight: 0,
            map: map
        });
				*/
	map.setCenter(latlngPos);
	//console.log(markers[index]);
	google.maps.event.trigger(markers[index], 'click');
               
}
//google.maps.event.addDomListener(window, 'load', initialize);
	
	
function addMarker(x,y,titulo,info,sucursalid){
setTimeout(function(){
	
	var html = $j("#"+sucursalid).html();
	//console.log(html);
	
  var infowindow = new google.maps.InfoWindow({
    content: html
  });

  var marker = new google.maps.Marker({
    position: {lat: x, lng: y},
    map: map,
    title: titulo,
		icon: "http://192.185.194.27/~adrianaarango/skin/frontend/parsonii/default/images/pin-tiendas.png"
  });
  marker.addListener('click', function() {
    infowindow.open(map, marker);
  });
	
	markers.push(marker);
}, 2000);	
}
</script>

<?php if($enable==1) { ?>

<body onload="loadMap('<?php  echo $latitudex ?>','<?php echo $longitudex; ?>','<?php echo $radius; ?>');">
<?php  $sql = $connection->query("select * from $tblname where status='0'" ); ?> 
<div class="maptiendas">
<div class="col-md-4 left">
	
<h3 class="title-store">Localizador de tienda</h3>
	
<?php 
							$cont = 0;
while($row = $sql->fetch()){
	$cont++;
if($row['radius']=='') { $radius1 = 250; } else { $radius1 = $row['radius']; }

?>
<script>
$j(function() {
addMarker(<?php echo $row['lat']; ?>,<?php echo $row['longt']; ?>,'<?php echo $row['name']; ?>','<?php echo $row['name']; ?>',"sucursal<?php echo $cont ?>");
});
</script>
	
<div class="tienda-store-locator store_name" onclick="map_xxx('<?php echo $row['lat']; ?>','<?php echo $row['longt']; ?>','<?php echo $radius1; ?>',<?php echo $cont-1 ?>);">

<?php if($image==1) { ?>
<td class="left">
<img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$row['image']; ?>" alt="<?php echo $row['name']; ?>" width="120" height="100" style="margin-right:5px;">
</td>
<?php } ?>

<div class="mintbl" id="sucursal<?php echo $cont ?>" style="min-width: 320px;">

<?php if($name==1) { ?>
<div class="info-locator col-icon"><?php echo $row['name']; ?></div>
<?php } ?>
<?php if($address==1) { ?>
<div class="info-locator col-address"><?php echo $row['address']; ?></div>
<?php } ?>
	
<div class="info-locator col-address">
<?php if($zipcode==1) { ?> 
Zip Code : <?php echo $row['zipcode']; ?> &nbsp;,
<?php } ?>
<?php if($city==1) { ?>
City : <?php echo $row['city']; ?> 
<?php } ?>
</div>

<?php if($country==1) { ?>
<div class="info-locator col-address col-icon">
Country : <?php echo $row['country_id']; ?> &nbsp;, 
<?php /* if($phone==1) { ?> <?php echo $row['phone']; ?> <?php } */ ?>
</div>
<?php } ?>
	
<?php if($phone==1) { ?>
<div class="info-locator col-icon">Tel: <?php echo $row['phone']; ?></div>
<?php } ?>
	
<?php if($fax==1) { ?>
<div class="info-locator col-icon"><?php echo $row['fax']; ?></div>
<?php } ?>
	
<?php if($email==1) { ?>
<div class="info-locator col-icon">Email: <?php echo $row['email']; ?></div>
<?php } ?>
</div>


<?php if($stireurl==1) { ?>
<tr><td colspan="2"> Website : <a href="<?php echo $row['store_url']; ?>" target="_blank"><?php echo $row['store_url']; ?></a></td></tr>
<?php } ?>
<?php if($description==1) { ?>
<tr><td colspan="2"> <?php echo $row['description']; ?></td></tr>
<?php } ?>
	
</div>

<?php   }  ?>

</div>
<div class="col-md-8">
<div id="map"></div>
</div>
		</div>

 
<?php } else { ?> 
<div ><h1 style="color:red;">Please Enable responsive banner Slider from <br/> Syestem-> Configuration-> Manv StoreLocator ->  Setting </h1></div>
 <?php } ?> 
